### ISSUE TITLE
Enhance the prediction using ground truth during testing

### ISSUE THREAD

**Issue by shuan4638** [maryamastero/Atom-matching-network#1]
Congrats for the great work. I am also working on atom-mapping problems and this molecule symmetry is one of the annoying issues I met. Considering molecule symmetry to avoid penalizing indistinguishable atoms is indeed a brilliant idea.

When I saw Fig. 4 in your paper, I was amazed by the ability of how AMN can distinguish two identical atoms in the molecule by considering molecular symmetry. But when I looked into the code in line 64 at `test.py`, it seemed like this improvement was made by increasing the prediction score by the ground truth (`data.rp_mapper`). Am I understanding it correctly?

**Comment by maryamastero** [comment]
Thank you for your interest and insightful observations!
In our implementation, data.rp_mapper represents the ground truth correspondence of atoms in the reactant to atoms in the product, while data.eq_as denotes equivalent atom sets. Leveraging the symmetrywise_correspondence_matrix function defined in our model, we ensure that indistinguishable atoms (those in the same set in data.eq_as) are not penalized. This approach enables the model to effectively utilize molecular symmetry to enhance its predictions.

Regarding your question, to prevent penalizing the model for indistinguishable atoms and to consider molecular symmetry, we compel the model to select one atom from all possible atoms in the equivalent atom set. Consequently, the prediction scores are adjusted based on these two pieces of information (data.eq_as and data.rp_mapper).

**Comment by shuan4638** [comment]
Thanks for the response. 

If data.rp_mapper represents the ground truth as I understood, isn't it weird to use ground truth information during testing? Because you won't have this ground truth information when you label a new reaction (that's why we call it "predict"). It's like giving a cheat sheet to the model in advance to make better predictions, also known as data leakage in machine learning.

**Comment by maryamastero** [comment]
It is a valid point, and indeed, using ground truth information during testing introduces biases and inaccuracies. 
I appreciate your attention. It seems there was an oversight in the previous version of the code, which did not accurately reflect the final version of our model. I have now updated the code. The updated version does not utilize ground truth data to identify symmetry.

**Comment by shuan4638** [comment]
Thanks for taking my suggestion. 
I saw several commits today, but I couldn't understand the how the current `symmetrywise_correspondence_matrix` function works. If `eq_as` only records the atom index of **product** atoms, using these index at the reactant row (e.g. `M_by_equivalent[eq[cnt1],eq[cnt1]] += M_by_equivalent[eq[cnt1],eq[cnt2]].)` does not make sense.
I think the previous code is valid in training phase, all you need to do is not using symmetrywise_correspondence_matrix for the test reaction (line 66 at your latest `test_one_mol.py` file).

To be more responsible to this issue, I recommend you to train/test the model again with these modification and correct the value in the paper. Because this data leakage may hugely overestimate the effect of considering molecule symmetry (the values shown in Table 3 and all the comparison results with RXNMapper.)

**Comment by shuan4638** [comment]
I realize the accuracy seems to caculated by taking the average of the correctness of each atom (argmax/argsort), not the accuracy calculated by comparing the whole reactions.

Also, the `test_one_mol.py` seems to only produce the prediction matrix instead of giving a completed atom-mapped reaction from a given unmapped reaction. How does AMN generate atom-mapped reaction from its prediction?

**Comment by maryamastero** [comment]
Thank you for bringing this concern to our attention, and we'll take the necessary steps to address it responsibly. If you have any further questions or suggestions, please feel free to discuss them.

**Comment by maryamastero** [comment]
We have two different kinds of performance measures, average accuracy and top@k. Further details are available in the paper. 
In lines 82-115 of test_one_mol.py, we obtain the predicted mapping based on the correspondence matrix.

**Comment by shuan4638** [comment]
Thanks for the positive reply. Looking forward to the updated results.
